MQTT_QUEUE_HOMEASSISTANT_NODE_ID_PREFIX = 'dachi_cloud_'
MQTT_QUEUE_HOMEASSISTANT_DEVICE_ID_PREFIX = 'device_id_'

MQTT_QUEUE_PROVIDER_TOPIC_CLIMATE_DEVICE = 'dachi_cloud_climate'
MQTT_QUEUE_PROVIDER_SUBSCRIBE_MASK = f'{MQTT_QUEUE_PROVIDER_TOPIC_CLIMATE_DEVICE}/#'